service:
  name: energy-usage-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  current-usage:
    handler: currentUsage.getCurrentUsage
    events:
      - http:
          method: get
          path: current
          cors: true
          authorizer: aws_iam
  usage-detail:
    handler: usageDetail.getUsageDetail
    events:
      - http:
          method: get
          path: usage-detail/{period}
          cors: true
          authorizer: aws_iam
  usage-summary:
    handler: usageSummary.getUsageSummary
    events:
      - http:
          method: get
          path: usage-summary/{period}
          cors: true
          authorizer: aws_iam
